export const theoryQuestions = [
  {
    question: "Câu 1: Kế toán là gì? Vai trò của kế toán?",
    answer: [
      "* Định nghĩa kế toán:",
      "Theo luật kế toán, kế toán là việc thu thập, xử lý, kiểm tra, phân tích, cung cấp thông tin kinh tế tài chính dưới hình thức giá trị hiện vật và thời gian lao động",
      "* Chức năng của kế toán:",
      "- Chức năng thông tin: kế toán theo dõi toàn bộ các hiện tượng kinh tế tài chính phát sinh trong quá trình hoạt động của doanh nghiệp",
      "- Chức năng kiểm tra: thông qua số liệu đã được phản ánh, kế toán nắm được quá trình và kết quả hoạt động của đơn vị, làm cơ sở cho việc đánh giá được đúng đắn, kiểm soát thực hiện mục tiêu và chấp hành luật pháp",
    ],
  },
  {
    question: "Câu 2: Trình bày nội dung các nguyên tắc kế toán ?",
    answer: [
      "- Nguyên tắc Cơ sở dồn tích",
      "Nguyên tắc này quy định những nghiệp vụ kế toán, tài chính của công ty có liên quan tới tài sản; nợ phải trả, doanh thu chi phí, nguồn vốn sở hữu,… Ngay thời điểm phát sinh, những thông tin này phải được ghi chép kỹ lưỡng vào sổ kế toán; không căn cứ theo thời điểm thu chi thực tế hay tương đương. ",
      "- Nguyên tắc hoạt động liên tục",
      "Báo cáo tài chính phải được lập dựa trên cơ sở công ty đang hoạt động và vẫn tiếp tục trong tương lai gần. Nếu thực tế khác với giả định thì báo cáo cần lập trên cơ sở khác và đưa ra một giải thích thích hợp về cơ sở mới. ",
      "- Nguyên tắc giá gốc",
      "Tài sản công ty phải được ghi nhận theo giá gốc (giá công ty cần chi để có được tài sản đó). Giá gốc được tính dựa trên số tiền hay khoản giá trị tương đương với số tiền đã thanh toán, phải trả hoặc tính theo giá trị phù hợp của tài sản đó được xác định ở thời điểm tài sản được ghi nhận. Giá gốc của tài sản thay đổi, kế toán không được tự ý điều chỉnh trừ khi có quy định khác cụ thể nằm trong luật kế toán, chuẩn mực kế toán.",
      "- Nguyên tắc phù hợp",
      "Nguyên tắc này nhắc nhở người dùng phải có sự phù hợp giữa việc ghi nhận về doanh thu và chi phí. Nếu người ghi nhận về một khoản doanh thu thì phải đưa ra được một khoản chi phí tương ứng liên quan. Khoản chi phí tương ứng với doanh thu gồm có khoản chi phí của kỳ trước hay là chi phí liên quan tới doanh thu kỳ đó.",
      "- Nguyên tắc nhất quán",
      "Cần có sự nhất quán trong một kỳ kế toán giữa những chính sách và phương pháp kế toán mà công ty đã áp dụng. Nếu chính sách hay phương pháp kế toán có sự thay đổi thì cần bổ sung giải trình lý do và sự tác động vào phần thuyết minh báo cáo.",
      "- Nguyên tắc thận trọng",
      "Nguyên tắc thận trọng yêu cầu kế toán cần phán đoán, xem xét và cân nhắc kỹ lưỡng, đưa ra những ước tính kế toán trong điều kiện không chắc chắn. Không lập những khoản dự phòng quá lớn, không đánh giá giá trị cao hơn các tài sản và khoản thu nhập cũng như không thấp hơn giá trị những khoản phải trả và chi phí.",
      "- Nguyên tắc trọng yếu",
      "Thông tin phụ thuộc vào độ lớn và tính chất của thông tin hoặc những sai sót trong một số hoàn cảnh cụ thể. Trường hợp bị thiếu thông tin hoặc thông tin không có sự chính xác cao có thể làm sai lệch báo cáo tài chính. Nguyên tắc này cần được xem xét kỹ lưỡng trên cả hai phương diện định lượng và định tính.",
    ],
  },
  {
    question: "Câu 3: Đối tượng, và hệ thống phương pháp kế toán?",
    answer: [
      "* Đối tượng của kế toán: là tài sản sở hữu và sự biến động của tài sản đó trong quá trình hoạt động của đơn vị. Xét cụ thể, đối tượng kế toán được phân biệt như sau: ",
      "1) Tài sản: các đối tượng phản ánh kết cấu của tài sản",
      "a) Tài sản ngắn hạn:  Tiền mặt, TGNH, nguyên vật liệu, sản phẩm, hàng hoá, nợ phải thu ngắn hạn …",
      "b) Tài sản dài hạn: các khoản phải thu dài hạn, Tài sản cố định, Bất động sản đầu tư, Các khoản đầu tư tài chính dài hạn…",
      "2) Nguồn vốn: các đối tượng phản ánh nguồn hình thành của tài sản",
      "a) Nợ phải trả: Nợ ngắn hạn, Nợ dài hạn",
      "b) Vốn chủ sở hữu: Vốn góp chủ sở hữu, Lợi nhuận chưa phân phối,…",
      "3) Các đối tượng phản ánh các quá trình kinh doanh: cho biết sự vận động chuyển hoá tài sản và nguồn vốn, bao gồm: doanh thu, thu nhập, chi phí …",
      "* Hệ thống phương pháp kế toán:",
      "1.	Chứng từ kế toán",
      "2.	Tài khoản kế toán",
      "3.	Ghi sổ kép",
      "4.	Tính giá các đối tượng kế toán",
      "5.	Kiểm kê",
      "6.	Báo cáo kế toán (Tổng hợp – Cân đối kế toán)",
    ],
  },
  {
    question:
      "Câu 4: Đối tượng sử dụng thông tin kế toán? Các yêu cầu đối với kế toán?",
    answer: [
      "* Đối tượng sử dụng thông tin kế toán:",
      "- Các nhà quản trị doanh nghiệp",
      "- Các ban lãnh đạo doanh nghiệp",
      "- Các cán bộ công nhân viên; Các cổ đông; Các chủ sở hữu",
      "- Các bên liên doanh; Các nhà tài trợ vốn; Các nhà đầu tư; Các chủ nợ",
      "- Khách hàng; Nhà cung cấp;",
      "- Cơ quan thuế; Cục thống kê",
      "- Các cơ quan quản lý nhà nước và cấp chủ quản",
      "* Các yêu cầu đối với kế toán:",
      "- Số liệu thông tin do kế toán cung cấp phải phản ánh trung thực, khách quan các hoạt động sản xuất kinh doanh của doanh nghiệp.",
      "- Số liệu thông tin kế toán phải phản ánh một cách kịp thời các nghiệp vụ kinh tế phát sinh trong doanh nghiệp.",
      "- Số liệu thông tin kế toán phải phản ánh đầy đủ, toàn diện mọi hoạt động sản xuất kinh doanh xảy ra ở đơn vị.",
      "- Số liệu thông tin kế toán phải rõ ràng, minh bạch.",
      "- Số liệu thông tin kế toán phải đảm bảo sự nhất quán về nội dung và phương pháp tính toán để đảm bảo so sánh được thông tin kế toán giữa các kỳ với nhau.",
      "- Tổ chức công tác kế toán đảm bảo yêu cầu tiết kiệm, hiệu quả.",
    ],
  },
  {
    question: "Câu 5: Trình bày khái niệm và kết cấu bảng cân đối kế toán?",
    answer: [
      "- Khái niệm: Bảng cân đối kế toán là một báo cáo tài chính tổng hợp phản ánh tổng quát tình hình tài sản và nguồn hình thành tài sản của doanh nghiệp tại một thời điểm nhất định.",
      "- Kết cấu của Bảng Cân đối kế toán:",
      "+ Kết cấu ngang: phần tài sản được trình bày bên trái, phần nguồn vốn bên phải",
      "+ Kết cấu dọc: phần tài sản được trình bày bên trên, phần nguồn vốn bên dưới",
      "Trong đó:",
      "+ Phần tài sản: trình bày các khoản mục liên quan đến tài sản theo quy định, phân thành 2 loại: A. Tài sản ngắn hạn và B. Tài sản dài hạn",
      "+ Phần nguồn vốn: trình bày các khoản mục liên quan đến nguồn vốn theo quy định, phân thành 2 loại: C. Nợ phải trả và D. Vốn chủ sở hữu",
      "Tổng tài sản = Tổng nguồn vốn",
    ],
  },
  {
    question:
      "Câu 6: Trình bày khái niệm và nội dung Báo cáo kết quả hoạt động kinh doanh?",
    answer: [
      "- Khái niệm: BCKQHĐKD là báo cáo tài chính tổng hợp, phản ánh tổng quát tình hình doanh thu, chi phí tạo ra doanh thu và kết quả kinh doanh do các hoạt động khác nhau của doanh nghiệp tạo ra trong một kỳ kế toán.",
      "- Nội dung của BCKQHĐKD gồm 19 chỉ tiêu, phần thành các nhóm:",
      "1.	Nhóm chỉ tiêu phản ánh doanh thu và thu nhập",
      "2.	Nhóm chỉ tiêu phản ánh chi phí tạo ra doanh thu và thu nhập",
      "3.	Nhóm chỉ tiêu phản ánh kết quả kinh doanh",
      "4.	Nhóm chỉ tiêu phản ánh chi phí thuế TNDN",
      "5.	Chỉ tiêu phản ánh lợi nhuận sau thuế",
    ],
  },
  {
    question: "Câu 7: Trình bày khái niệm tài khoản. Cho ví dụ về tài khoản",
    answer: [
      "- Khái niệm: Tài khoản kế toán là phương pháp kế toán dùng để phân loại đối tượng của hạch toán kế toán nhằm phản ánh thường xuyên, liên tục và có hệ thống tình hình hiện có và sự biến động của từng đối tượng kế toán cụ thể",
      "Mỗi tài khoản có số hiệu và tên gọi riêng, phù hợp với nội dung kinh tế của đối tượng ghi nhận",
      "Ví dụ: để theo dõi TSCĐ hữu hình  mở tài khoản “Tài sản cố định hữu hình”, số hiệu 211",
    ],
  },
  {
    question:
      "Câu 8: Trình bày kết cấu tài khoản và nguyên tắc phản ánh trên tài khoản.",
    answer: [
      "- Kết cấu tài khoản: tài khoản được chia thành 2 bên để phản ánh 2 mặt đối lập gồm: bên trái tài khoản gọi là bên nợ, bên phải tài khoản gọi là bên có",
      "- Nguyên tắc phản ánh trên tài khoản:",
      "+ Nhóm tài khoản tài sản:",
      "Bên nợ:",
      "- Số dư đầu kỳ",
      "- Số phát sinh tăng trong kỳ",
      "- Số dư cuối kỳ",
      "Bên có:",
      "- Số phát sinh giảm trong kỳ",
      "Số dư cuối kỳ = Số dư đầu kỳ + Số phát sinh tăng trong kỳ - Số phát sinh giảm trong kỳ",
      "+ Nhóm tài khoản nguồn vốn:",
      "Bên nợ:",
      "- Số phát sinh giảm trong kỳ",
      "Bên có:",
      "- Số dư đầu kỳ",
      "- Số phát sinh tăng trong kỳ",
      "- Số dư cuối kỳ",
      "+ Nhóm tài khoản trung gian:",
      "Bên nợ:",
      "- Chi phí tăng",
      "- Doanh thu, thu nhập giảm",
      "- Các khoản được kết chuyển",
      "Bên có:",
      "- Chi phí giảm",
      "- Doanh thu, thu nhập tăng",
      "- Các khoản được kết chuyển",
      "Không có số dư",
    ],
  },
  {
    question: "Câu 9: Trình bày khái niệm ghi sổ kép. Cho ví dụ minh hoạ",
    answer: [
      "- Khái niệm: Ghi sổ kép là phương pháp ghi chép số tiền của các nghiệp vụ kinh tế phát sinh vào các tài khoản có liên quan căn cứ vào nội dung kinh tế của nghiệp vụ và mối quan hệ giữa các đối tượng với nhau. Thực chất là ghi Nợ tài khoản này và ghi Có tài khoản khác có quan hệ đối ứng với nó với cùng một số tiền.",
      "Ví dụ: Doanh nghiệp gửi 700 tiền mặt vào tài khoản mở tại ngân hàng. Nghiệp vụ này liên quan đến sự biến động của tiền mặt và tiền gửi ngân hàng theo chiều hướng tăng tiền gửi và giảm tiền mặt. ",
      "Nợ tài khoản “Tiền gửi ngân hàng”	700",
      "Có tài khoản “Tiền mặt”			700",
    ],
  },
  {
    question: "Câu 10: Trình bày khái niệm tính giá và các nguyên tắc chi phối?",
    answer: [
      "- Khái niệm: Tính giá là phương pháp kế toán biểu hiện giá trị các đối tượng kế toán bằng tiền phù hợp với các nguyên tắc kế toán và quy định nhà nước",
      "- Các nguyên tắc chi phối:",
      "+ Nguyên tắc hoạt động liên tục",
      "+ Nguyên tắc giá gốc",
      "+ Nguyên tắc thận trọng",
      "+ Nguyên tắc nhất quán",
      "+ Nguyên tắc khách quan",
    ],
  },
  {
    question: "Câu 11: Trình bày công thức tính giá TSCĐ được mua sắm?",
    answer: [
      "TSCĐ được phản ánh theo nguyên giá và giá trị còn lại",
      "Nguyên giá = Giá mua thực tế + Chi phí trước khi sử dụng + Khoản khác liên quan",
      "Giá trị còn lại = Nguyên giá – Giáo trị hao mòn",
    ],
  },
  {
    question:
      "Câu 12: Trình bày công thức tính giá nhập kho khi mua ngoài của hàng tồn kho?",
    answer: [
      "Giá nhập kho = Giá mua + Chi phí mua – Chiết khấu thương mại, giảm giá hàng mua",
      "Trong đó: Chi phí mua gồm: chi phí vận chuyển, bốc xếp, bảo quản, …",
    ],
  },
  {
    question: "Câu 13: Liệt kê các phương pháp tính giá xuất kho của hàng tồn kho?",
    answer: [
      "Có 3 phương pháp tính giá xuất kho: thực tế đích danh, nhập trước xuất trước, bình quân gia quyền",
    ],
  },
  {
    question:
      "Câu 14: Trình bày khái niệm chứng từ kế toán. Liệt kê các bước xử lý chứng từ?",
    answer: [
      "- Khái niệm: chứng từ kế toán là những giấy tờ và vật mang tin phản ánh nghiệp vụ kinh tế, tài chính phát sinh và đã hoàn thành, làm căn cứ ghi sổ kế toán.",
      "- Trình tự xử lý chứng từ kế toán:",
      "1.	Kiểm tra chứng từ",
      "2.	Hoàn chỉnh chứng từ",
      "3.	Luân chuyển chứng từ",
      "4.	Bảo quản chứng từ",
    ],
  },
  {
    question: "Câu 15: Trình bày khái niệm kiểm kê. Phân loại kiểm kê.",
    answer: [
      "- Khái niệm: Kiểm kê là phương pháp kiểm tra tại chỗ các loại tài sản hiện có nhằm xác định chính xác số lượng, chất lượng cũng như giá trị của các loại tài sản hiện có.",
      "- Phân loại kiểm kê:",
      "+ Căn cứ theo thời điểm kiểm kê: kiểm kê định kỳ và kiểm kê đột xuất",
      "+ Căn cứ theo phạm vi kiểm kê: kiểm kê toàn bộ và kiểm kê từng phần",
    ],
  },
  {
    question: "Câu 16: Trình bày khái niệm sổ kế toán. Cho ví dụ sổ kế toán",
    answer: [
      "- Khái niệm: Sổ kế toán là những tờ sổ được xây dựng theo những mẫu nhất định có liên hệ chặt chẽ với nhau, dùng để ghi chép các nghiệp vụ kinh tế theo đúng phương pháp kế toán, trên cơ sở số liệu của chứng từ kế toán, nhằm cung cấp thông tin phục vụ công tác lãnh đạo và quản lý các hoạt động kinh tế tài chính trong đơn vị.",
      "Ví dụ: Sổ nhật ký chung, sổ cái tài khoản…",
    ],
  },
];
